---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: qa
          value: "prod-us"
        - name: GPU_ENABLED
          value: "1"
      